### ISSUE TITLE
README and docs out of sync

### ISSUE THREAD

**Issue by philgyford** [mgan59/python-pinboard#11]
The README says to do this to install python-pinboard:

```
pip install -e git://github.com/mgan59/python-pinboard.git@v1.0#egg=python-pinboard
```

but this results in a version where the `open()` method only accepts `username` and `password`, and has no mention of using `token` (which is suggested in the docs). Maybe the docs are just ahead of v1.0, or there needs to be a new version number?

This is the version of the `open()` method installed as v1.0:

```
def open(username, password):
    """Open a connection to a pinboard.in account"""
    return PinboardAccount(username, password)
```

**Comment by mgan59** [comment]
k had a chance to look at what is going on.  So I need to update the code and create a `v1.1` release as a tag and link to it.  Thanks for catching this Phil I'll make the necessary changes.

**Comment by mgan59** [comment]
okay I did a couple of things.  

I updated the readme to now include all the usage notes and going forward we should use the github readme for documenting usage :+1:  

Secondly I created a new tag for 1.1 - https://github.com/mgan59/python-pinboard/tree/v1.1 and updated the readme's installation notes to install from that tag which will include the changes to the `.open` interface that supports `token=''`

Thanks for catching all this @philgyford and feel free to send a pull-request if you see anything else :)

**Comment by philgyford** [comment]
Brilliant, thanks @mgan59 !
